"""ANS/RNS computation and validation toolkit."""

from .api import (
    DGNInferenceConfig,
    DGNModelBundle,
    HemisphereClassificationConfig,
    HemisphereClassificationResult,
    MetricComputeConfig,
    MetricComputeResult,
    PipelineRunConfig,
    PipelineRunResult,
    PreprocessingSpec,
    ValidationConfig,
    ValidationRunResult,
    ValidationSummaryRow,
    compute_ans_rns_arrays,
    compute_metrics,
    default_classifier_output_path,
    default_input_glob,
    default_trt_output_path,
    discover_local_dgn_bundles,
    get_preprocessing_spec,
    infer_dgn_direction_from_path,
    normalize_dgn_direction,
    resolve_classifier_model_dir,
    resolve_dgn_model_root,
    resolve_glasser_atlas_path,
    resolve_glasser_label_table,
    resolve_validation_hemis,
    run_dgn_inference,
    run_pipeline,
    target_hemisphere_for_direction,
    validate_reliability,
    validate_hemisphere_classification,
    validate_specificity,
)
from .roi import RoiSummaryConfig, summarize_maps_by_atlas
from .workflow import (
    BilateralWorkflowConfig,
    BilateralWorkflowResult,
    run_bilateral_workflow,
    summarize_bilateral_roi_features,
    summarize_subject_metrics,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "DGNInferenceConfig",
    "BilateralWorkflowConfig",
    "BilateralWorkflowResult",
    "DGNModelBundle",
    "HemisphereClassificationConfig",
    "HemisphereClassificationResult",
    "MetricComputeConfig",
    "MetricComputeResult",
    "PipelineRunConfig",
    "PipelineRunResult",
    "PreprocessingSpec",
    "RoiSummaryConfig",
    "ValidationConfig",
    "ValidationRunResult",
    "ValidationSummaryRow",
    "compute_ans_rns_arrays",
    "compute_metrics",
    "default_classifier_output_path",
    "default_input_glob",
    "default_trt_output_path",
    "discover_local_dgn_bundles",
    "get_preprocessing_spec",
    "infer_dgn_direction_from_path",
    "normalize_dgn_direction",
    "resolve_classifier_model_dir",
    "resolve_dgn_model_root",
    "resolve_glasser_atlas_path",
    "resolve_glasser_label_table",
    "resolve_validation_hemis",
    "run_dgn_inference",
    "run_bilateral_workflow",
    "run_pipeline",
    "target_hemisphere_for_direction",
    "validate_reliability",
    "validate_hemisphere_classification",
    "validate_specificity",
    "summarize_maps_by_atlas",
    "summarize_bilateral_roi_features",
    "summarize_subject_metrics",
]
